### ISSUE TITLE
Improve raw handling in suggest_bads

### ISSUE THREAD

**Issue by pravsripad** [jdammers/jumeg#139]
Suggestions for improving the general function call:

raw, _ = jumeg_base.update_bad_channels(fif_raw,raw=raw,bads=bads_list,save=True)

-> check if raw is not none else load fif file
  if save:
     preload = True

**Comment by jdammers** [comment]
@pravsripad I suggest to also allow for 'other' raw objects for example 'RawCTF' which is the name of the object type when imported by mne.io.read_raw_ctf()

**Comment by pravsripad** [comment]
@nkampel could you have a look at this and try to modify the function call as described above?

**Comment by nkampel** [comment]
ill try!

**Comment by pravsripad** [comment]
> ill try!

Cool, welcome to github. 👍

**Comment by pravsripad** [comment]
@nkampel @jdammers so, jumeg_base.update_bad_channels already handles this using get_raw_obj. 

Raw is handled, but not RawCTF, maybe @fboers can include this suggestion in next version of jumeg_base.py. 

https://github.com/jdammers/jumeg/blob/854faba429215ca95073b438364edbb2ab67ca29/jumeg/base/jumeg_base.py#L1400
