### ISSUE TITLE
ica._pre_whiten() affecting results of ica in do_MLICA.py

### ISSUE THREAD

**Issue by ckiefer0** [jdammers/jumeg#159]
Hello @pravsripad , @asmasbaih3000

I opened a separate issue but in principle the problem is similar to issue [#151](https://github.com/jdammers/jumeg/issues/151).

The reason why we get two different plots in do_MLICA.py is because in my version of mne I changed a line in ica._pre_whiten() and not because we use mne v0.14 or mne v0.15.

In my version of ICA.py I have in line ~528

     pre_whitener[this_picks] = np.std(data[this_picks], axis=1)[:, None]

instead of

     pre_whitener[this_picks] = np.std(data[this_picks])

Since ica.pre_whiten() is called by ica.fit() and it changes the results so drastically, it does not seem to be sufficient to change ica._pre_whitener after fitting.

Can you replicate the results? Do we get the same results for different data sets?

Here are the two plots again:
 First one using axis=1:
![109925_cau01a_100715_0842_2_c rfdc 0-45hz ar-perf](https://user-images.githubusercontent.com/25769508/42506166-637141da-8441-11e8-99f5-4ce4a1810658.png)

Second one using the original version without axis=1:

![109925_cau01a_100715_0842_2_c rfdc 0-45hz ar-perf](https://user-images.githubusercontent.com/25769508/42505806-2dc6a94a-8440-11e8-8e02-33024b161ab4.png)

**Comment by ckiefer0** [comment]
Here is the result for using only mne methods. Mixing both methods is definitely not a good idea.

![109925_cau01a_100715_0842_2_c rfdc 0-45hz ar-perf_mne](https://user-images.githubusercontent.com/25769508/42631407-6d0868aa-85da-11e8-898d-ea257c09b1b7.png)

**Comment by pravsripad** [comment]
@ckiefer0 This is solved by #164 correct?

**Comment by ckiefer0** [comment]
Yes, you are correct.
