### ISSUE TITLE
plot_powerspectrum

### ISSUE THREAD

**Issue by jdammers** [jdammers/jumeg#169]
I would appreciate to have the same (optional) arguments as provided by the raw.plot_psd() function. In particular, **average=False**  would be very helpful to identify (or double check for) bad channels. Also *dB=True* or *dB=False* is missing.

**Comment by jdammers** [comment]
for **dir_plots='plots'** we should also allow for being set to *None*.
I would argue setting the defaults of **fmin** and **fmax** to None and determine the values (if not provided to the possible range defined by the analog filter (e.g. DC => fmin=0.0) and the Nyquist frequency defined by the sampling rate (e.g. srate=1017.25 => fmax=floor(srate/2.))

**Comment by jdammers** [comment]
picks = jumeg_base.pick_meg_nobads(raw)  should read 
 picks = jumeg_base.picks.meg_nobads(raw)  or even better
** picks = jumeg_base.picks.meg(raw)**  to allow for identification of bads missed by suggest_bads (and after interpolation)

**Comment by jdammers** [comment]
Parameter to fix the y-axis range is also missing. Suggestion: 
ax.set_ylim([ymin, ymax])

**Comment by pravsripad** [comment]
> I would appreciate to have the same (optional) arguments as provided by the raw.plot_psd() function. In particular, **average=False** would be very helpful to identify (or double check for) bad channels. Also _dB=True_ or _dB=False_ is missing.

@jdammers The plot_powerspectrum now takes all kwargs used by raw.plot_psd().

**Comment by pravsripad** [comment]
> for **dir_plots='plots'** we should also allow for being set to _None_.
> I would argue setting the defaults of **fmin** and **fmax** to None and determine the values (if not provided to the possible range defined by the analog filter (e.g. DC => fmin=0.0) and the Nyquist frequency defined by the sampling rate (e.g. srate=1017.25 => fmax=floor(srate/2.))

Has also been resolved. If dir_plots is None, then the plot will be saved in the current directory.

**Comment by pravsripad** [comment]
> picks = jumeg_base.pick_meg_nobads(raw) should read
> picks = jumeg_base.picks.meg_nobads(raw) or even better
> **picks = jumeg_base.picks.meg(raw)** to allow for identification of bads missed by suggest_bads (and after interpolation)

Uses **picks = jumeg_base.picks.meg(raw)** now.

**Comment by pravsripad** [comment]
There is also another function to plot PSDs, which do you use? @jdammers @fboers 

https://github.com/jdammers/jumeg/blob/80af54db78579b36b104e64a02703b41fb856e57/jumeg/plot/jumeg_plot_preproc.py#L267

**Comment by jdammers** [comment]
@pravsripad: in Nov/2018 I was using plot_powerspectrum()
