### ISSUE TITLE
jumeg_suggest_bads.py", line 481 SyntaxError: Missing parentheses 

### ISSUE THREAD

**Issue by fboers** [jdammers/jumeg#172]
from jumeg.jumeg_suggest_bads     import suggest_bads
  File "/home/fboers/MEGBoers/megtools/python/jumeg/jumeg_suggest_bads.py", line 481
    print 'epoch_length of %d chosen' % epoch_length
                                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('epoch_length of %d chosen' % epoch_length)?

**Comment by pravsripad** [comment]
Automatically resolved after switch to py3.
