### ISSUE TITLE
jumeg_filter:  postfix generation for filename incorrect for highpass cut off frequency

### ISSUE THREAD

**Issue by jdammers** [jdammers/jumeg#173]
when using the jumeg_filter object to generate the postfix for the output filename, the postfix is incorrect for floating point high pass cut-off frequencies such as 0.1 Hz. For example, when using a bandpass filter from 0.1-100 Hz the output postfix will be 'fibp0-100'  instead of 'fibp0.1-100'

**Comment by ckiefer0** [comment]
It seems like this has been fixed already. Can you confirm?

**Comment by pravsripad** [comment]
Can confirm that it has been fixed. But I found another bug in jumeg_filter using mne. I'll make another issue for it.
