### ISSUE TITLE
suggestions to label or how to number files in pipeline

### ISSUE THREAD

**Issue by fboers** [jdammers/jumeg#184]
would like to put 2 files in pipeline folder
jumeg_io_import_to_fif.py
jumeg_io_merge_meeg.py
any suggestions to label or how to number e.g
1000 +x for basic IO? 
2000 => preproc  BADs  NR  Filter ICA?

1010_jumeg_io_import_to_fif.py
1020_jumeg_io_merge_meeg.py

**Comment by pravsripad** [comment]
Currently using in the pipelines, 
```
1_preprocessing.py
2_artifact_rejection.py
3_prepare_epochs.py
4_covariance_matrices.py
5_setup_source_localization.py
6_do_source_localization.py
```
