### ISSUE TITLE
jumeg_interpolated_bads  error in mne-version0.20

### ISSUE THREAD

**Issue by fboers** [jdammers/jumeg#241]
File .../anaconda3/envs/jumeg-0.20.0/lib/python3.6/site-packages/jumeg/jumeg_interpolate_bads.py", line 51, in interpolate_bads

    _interpolate_bads_eeg(inst)
TypeError: _interpolate_bads_eeg() missing 1 required positional argument: 'origin'

suggestion:
def interpolate_bads(inst, reset_bads=True, mode='accurate', origin=None, verbose=None):
    ... 
=> first check if EEG in raw
picks_eeg = pick_types(inst.info, meg=False, eeg=True, exclude=[])
if picks_eeg is not None:
  #--- ck for origin  or mne version
     if  'origin' in _interpolate_bads_eeg.__code__.co_varnames:
        _interpolate_bads_eeg(inst,origin)  # mne 0.20
    else:
       _interpolate_bads_eeg(inst)    mne <0.20

bests Frank

**Comment by pravsripad** [comment]
Hello @fboers , I think simply making the below change would suffice,
```
    _interpolate_bads_eeg(inst, origin)
```

_interpolate_bads_eeg already has check in it for EEG picks, so checking for that condition is not necessary. 

Also, do we really need compatibility with older mne versions?

**Comment by fboers** [comment]
Hello @pravsripad, 
you are right
this code see below is a work around for older mne versions,
you can delete it  and use  _interpolate_bads_eeg(inst, origin)
bests Frank

#--- check if EEG in raw
    picks_eeg = pick_types(inst.info, meg=False, eeg=True, exclude=[])
    if picks_eeg is not None:
   #--- ck for origin or mne version  FB 2020-05-20 PY3
       if 'origin' in _interpolate_bads_eeg.__code__.co_varnames:
           _interpolate_bads_eeg(inst,origin) # mne 0.20
       else:
           _interpolate_bads_eeg(inst) # mne <0.20
   
    _interpolate_bads_meg(inst, origin=origin, mode=mode)
