### ISSUE TITLE
jumeg import error

### ISSUE THREAD

**Issue by jdammers** [jdammers/jumeg#253]
I am running the MNE version 0.21. When trying to import the latest jumeg repo I get the follwing import error within jumeg_interpolate_bads:
`ImportError: cannot import name '_map_meg_channels' from 'mne.forward' (/home/jdammers/anaconda3/envs/jumeg_cuda/lib/python3.8/site-packages/mne/forward/__init__.py)`

Does anybody know how to solve this?

**Comment by pravsripad** [comment]
The issue should be solved by the above PR.

**Comment by jdammers** [comment]
@pravsripad many thanks,  it works for me
