### ISSUE TITLE
noise_reducer  error for time.clock() -> function in removed  =>python3.8

### ISSUE THREAD

**Issue by fboers** [jdammers/jumeg#265]
ERROR:
File "...../lib/python3.9/jumeg/jumeg_noise_reducer.py", line 441, in noise_reducer
    tc0 = time.clock()
AttributeError: module 'time' has no attribute 'clock'

e.g. solution or use time.time()
https://github.com/wxWidgets/Phoenix/issues/1510

rest of NR is running smooth

**Comment by ebeich** [comment]
Just replace time.clock() by time.perf_counter()

On 20.01.22 17:36, fboers wrote:
> ERROR:
> File "...../lib/python3.9/jumeg/jumeg_noise_reducer.py", line 441, in noise_reducer
>      tc0 = time.clock()
> AttributeError: module 'time' has no attribute 'clock'
>
> e.g. solution or use time.time()
> https://github.com/wxWidgets/Phoenix/issues/1510
>
> rest of NR is running smooth
>



------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
Forschungszentrum Juelich GmbH
52425 Juelich
Sitz der Gesellschaft: Juelich
Eingetragen im Handelsregister des Amtsgerichts Dueren Nr. HR B 3498
Vorsitzender des Aufsichtsrats: MinDir Volker Rieke
Geschaeftsfuehrung: Prof. Dr.-Ing. Wolfgang Marquardt (Vorsitzender),
Karsten Beneke (stellv. Vorsitzender), Prof. Dr. Astrid Lambrecht,
Prof. Dr. Frauke Melchior
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
