### ISSUE TITLE
ERROR in  ica_artefact_rejection_and_appl with mne.0241 pre_whiten() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by fboers** [jdammers/jumeg#268]
return ica_artefact_rejection_and_apply(raw,ICA,picks=picks,reject=reject)
  File "~/python/anaconda3/envs/jumeg241/lib/python3.9/jumeg/base/pipelines/jumeg_pipelines_ica_utils.py", line 398, in ica_artefact_rejection_and_apply
    data,_     = ica_obj._pre_whiten(data,_raw.info,picks)  # works inplace
TypeError: _pre_whiten() takes 2 positional arguments but 4 were given

**Comment by jdammers** [comment]
@fboers I cannot reproduce the error. The file jumeg_pipelines_ica_utils.py seems not to be on master (?)
