### ISSUE TITLE
the performance of 'apply_ica_cleaning'

### ISSUE THREAD

**Issue by dongqunxi** [jdammers/jumeg#50]
@jdammers @pravsripad @lukasbreuer I tested the new apply_ica_cleaning, but the results are not so good as I used my old version before. I use the subject '101611', the EOG rejection is bad. Please confirm it, thanks!

**Comment by pravsripad** [comment]
@dongqunxi Is this issue fixed?

**Comment by dongqunxi** [comment]
@pravsripad Yes you can delete it

**Comment by pravsripad** [comment]
@dongqunxi Thanks, I will do so.
